var strings = {
    'TITLE': '러브앤프로듀서 계산기',
    'SUB_TITLE': '러브앤프로듀서 계산기v2.0',
    'PREV_VERSION': 'v1버전',
    'HELP': '사용 설명',
    'BROWER_NOT_SUPPORTED': '당신의 브라우저는 이 버전을 지원되지 않는다.  Chrome 브라우저에 시도 해 볼 수 있습니다.',
    'SWITCH_NAV': '전환 안내',
    'NAV_LEVEL': '관문 계산',
    'NAV_TICKET': '시청률 쟁탈전 ',
    'NAV_CHALLENGE': '24시간 도전',
    'NAV_DOUBLE': '카팀 분석',
    'NAV_CARD': '나의 운명',
    'NAV_LOGIN': '계정 로그인',
    'NAV_SWITCH': '계정 변경',
    'COMPANY_PROPS': '회사 속성',
    'DECISIVENESS': '결단',
    'CREATIVITY': '창의',
    'KINDNESS': '친화',
    'ACTIVITY': '추진',
    'SAVE': '보존',
    'SAVING': '보존 중',
    'LOADING': '로딩 중',
    'SWITCH': '토글',
    'LOGOUT': '로그아웃 ',
    'TIP_DATA_ONLINE': '현재의 데이터 저장하고, 다음에 이용 할 수 있도록 비밀번호를 기억 하세요.',
    'DATA_PRESERVE': '온라인 저장',
    'TIP_DATA_OFFLINE_FIRST': '현재 데이터는 브라우저에 저장',
    'TIP_DATA_OFFLINE_OR': '혹은',
    'TIP_DATA_OFFLINE_LAST': '온라인 개인 정보과 회사를 저장',
    'CREATE': '창건',
    'LOGIN': '로그인',
    'CREATE_USER': '창건 회사',
    'LOGIN_USER': '입사',
    'ADD_CARD': '나의 운명를 첨가하다',
    'LABEL_ADD_CARD': '키워드를 입력하고, 첨가 혹 수정 나의 운명',
    'HELP_ADD_CARD': '추가 할 때 먼저 등급을 입력하고, 자동으로 속성값를 추산하다.',
    'EXPORT': '도출',
    'IMPORT': '도입',
    'BATCH_EXPORT': '대량 도출',
    'BATCH_IMPORT': '대량 도입',
    'TIP_IMPORT_PART_FAIL': '이하 도입 실패, 이름이 올바른지 확인해 주세요.',
    'SOURCE': '데이터 출처',
    'GROUP_ACCOUNT': '@恋与制作人未命名攻略组',
    'TIP_SOURCE': '가중 데이터 출처 ',
    'TIP_CREATOR': '계산기 제작은 @达尔娜 @清澄 @鱼骨头',
    'TIP_HELP_FIRST': '처음 사용하기 전에 ',
    'TIP_HELP_AND': '과',
    'TIP_HELP_SUPPORT': '지지',
    'TIP_HELP_LAST': '。',
    'TIP_FEATURE': '기능',
    'MY_CARD': '나의 운명',
    'CLEAR_DATA': '데이터 비우기',
    'CHARACTOR': '인물',
    'ALL': '전부',
    'LIZEYAN': '이택언',
    'XUMO': '허묵 ',
    'ZHOUQILUO': '주기락 ',
    'BAIQI': '백기',
    'OTHER': '기타',
    'RARE': '희귀도',
    'FILTER': '선별',
    'NAME': '이름',
    'LEVEL': '등급',
    'OPTIONS': '조작',
    'MODIFY': '수정',
    'DELETE': '삭제',
    'ADD_TO_CHALLENGE': '가입24H',
    'EXPAND': '펼쳐',
    'COLLAPSE': '철수',
    'ALL_CARDS': '모든 운명',
    'ADD_ALL_CARD': '전부를 첨가하다 (만렙)',
    'ADDED': '이미 첨가됨',
    'ADD_NEW_EVOLED_CARD': '새로운 만렙카드를 첨가하다',
    'ADD_EVOLED_CARD': '만렙카드를 첨가하다',
    'ADD_NORMAL_CARD': '미진화카드를 첨가하다',
    'ADD_CUSTOM_CARD': '자체정의를 첨가하다.',
    'ADD_MORE_CARD': '더 많은 운명를 첨가하다.',
    'ADD': '첨가',
    'TIP_ADD': '3장 이상 운명를 개방하다',
    'CATEGORY': '종별',
    'CHAPTER': '장절',
    'CHAPTER_BEFORE': '제',
    'CHAPTER_AFTER': '장',
    'LEVELS': '관문',
    'CALCULATE': '계산',
    'DROP': '떨어진 ',
    'GOODS': '관문 떨어진',
    'PROP_REQUIRE': '실력 요구',
    'SPEC_REQUIRE': '특수 요구	',
    'RECOMMEND': '추천',
    'RECOMMEND_CARD': '고점 운명',
    'SCORE': '득점',
    'RANK': '등급평가',
    'COMPANY_SCORE': '회사 득점',
    'STAFF_SCORE': '전문가 득점',
    'CARD_SCORE': '운명 득점',
    'NO_SETTING': '미설정',
    'TOTAL_SCORE': '총점',
    'TIP_MODIFY': '위에 클릭면 변경될 수 있습니다',
    'ONE_STAR': '1스타',
    'TWO_STAR': '2스타',
    'THREE_STAR': '3스타',
    'STAR': '성급',
    'STAR_AFTER': '스타',
    'NO_DATA': '데이터가 없다',
    'HELP_LEVEL': '관문을 통과점수 오차가 있을 수 있습니다, 참고용으로만 제공합니다. 통과 때 신중해야 한다.',
    'CARD_ANALYSE': '운명 분석',
    'CONFIG': '설치',
    'ALL_CARD': '모든 운명',
    'HIDDEN': '숨기다',
    'NOT_CHANGE': '바뀌지 않다',
    'NORMAL': '진화 전 ',
    'EVOLVED': '진화 후',
    'LOW_LEVEL': '초급카드',
    'OLD_EVOLVED': '만렙카드',
    'NEW_EVOLVED': '새로운 만렙카드',
    'HELP_CONFIG': '설치 변경 운명속성, 관문통과 분석을 진행 할 수 있습니다.',
    'HELP_CONFIG_ADDITION': '보라색은 이미 얻었다는 뜻입니다',
    'TICKET_TODAY': '오늘 시청률',
    'THEME': '주제',
    'CLOSE': '닫기',
    'GUEST': '게스트',
    'WINNING_ANALYSE': '승률 분석',
    'TICKET_CALCULATE': '시청률 계산',
    'MY_TEAM': '나의 진영',
    'MATCH_TEAM': '상대방 진영',
    'SCORE_COMPARE': '득점 대조',
    'MINE': '자신',
    'MY': '나의 ',
    'MATCH': '상대방',
    'TEAM': '진영',
    'SCORE_DIFF': '점수 차',
    'GUARD': '수호',
    'TOGGLE': '펼쳐/자세한 사항은 닫기',
    'PROP_COMPARE': '실력 대조',
    'COMPANY_COMPARE': '회사 대조',
    'CARD_COMPARE': '운명 대조',
    'SUM': '총계',
    'FIRST_LEVEL': '첫 관문',
    'LEVEL_ANALYSE': '관문통과 분석',
    'DAMAGE': '소모',
    'RECORD': '기록',
    'HISTORY': '역사',
    'SN': '번호',
    'COMPANY_PROP': '회사 실력',
    'CARD_PROP': '운명 실력',
    'BUFF': '가성',
    'CARD': '운명',
    'RECORD_DAMAGE': '소모 기록',
    'RETRACT_DAMAGE': '소모 철수',
    'RESET_DAMAGE': '리셋 소모',
    'GUARD_SCORE': '수호 득점',
    'CLEAR_CARD': '출진 운명을 완전히 없애다',
    'NEXT_LEVEL': '다음 관문',
    'RECOMMEND_CARDS': '카팀 추천',
    'TIP_TICKET_FIRST': '쌍방 회사 속성이 같다고 묵인하다면 참고용으로만 제공합니다.  필요 하시다면 속성이 대조해서 점수를 따다.',
    'TIP_TICKET_LAST': '추산 상대방 회사 속성',
    'USE': '사용',
    'CLEAR_HISTORY': '역사기록을 완전히 없애다 ',
    'CURRENT': '현재',
    'THRESHOLD': '차분 역치',
    'RESET': '리셋',
    'STATUS': '상태',
    'REMOVE': '제거',
    'PLAYED': '이미 출전',
    'WEIGHT': '가중',
    'UPDATE': '갱신',
    'SHOW': '현시',
    'VALUE': '속성값',
    'RATE': '속성 비율',
    'DECISIVENESS_GROUP': '결단팀 ',
    'CREATIVITY_GROUP': '창의팀',
    'KINDNESS_GROUP': '친화팀',
    'ACTIVITY_GROUP': '추진팀 ',
    'GAIN': '획득',
    'HELP_DOUBLE': '클릭설치 자체 정의 표시항목',
    'HELP_DOUBLE_ADDITION': '보라색은 이미 운명를 얻었다는 뜻입니다',
    'PROP_COMBINE': '속성 조합',
    'CARD_COMBINE': '고점 카팀',
    'NA': '아직 없다',
    'CURRENT_ACCOUNT': '현재 계정',
    'COMPANY_NAME': '회사 이름',
    'PASSWORD': '비밀번호 보호',
    'TIP_LOGIN': '회사 이름을 반복될 수 없습니다, 비밀번호 보호 설치 하지 않아도 됩니다, 비밀번호 보호 설치면 데이터 가 다른 사람에게 수정 되는 것을 방지 할 수 있습니다.',
    'HISTORY_ACCOUNT': '역사적 기록 ',
    'CANCEL': '취소',
    'CONFIRM': '확인',
    'LOGINING': '로그인 중',
    'NOT_EVOLVED': '미진화',
    'IS_EVOLVED': '진화',
    'EVOLVE': '진화',
    'TIP_CARD': '데이터를 자동으로 계산하면 오차 가 있을 수 있습니다, 수정이 필요하다면 대조해 주세요',
    'SAVE': '보존',
    'SAVING': '보존 중',
    'CARD_NAME': '운명 이름',
    'MULTIPLY': '배수',
    'TIP_THRESHOLD': '어느 수치 보다 점수 차를 더높고 이용해서 판단 관문을 통과할 수 있을지 없을지.  이래야 모르 회사 데이터 균형 수 있습니다.',
    'TOTAL_PROP': '총 실력',
    'FILL_IN_AVRAGE': '평균 삽입',
    'TIP_CHALLENGE': '회사 데이터가 모른다면, 총 실력을 따라 평균분배 수 있습니다',
    'TIP_CHOOSE_CARD': '이름 클릭고 출진 운명을 선택하기',
    'CANCEL_PLAY': '출진 취소',
    'MODE': '모드',
    'HURT': '마손 카드',
    'HIDE_LOW_LEVEL': '저급 카드 숨기다',
    'HURTING': '닳다',
    'DAMAGING': '손상',
    'HURT_PER_DAMAGE': '단위 수익',
    'VIEW_HEAD': '프로필 사진 보기',
    'IMAGE_LOADING': '사진 로딩 중',
    'SHOW_HEAD': '프로필사진 현시하기',
    'COLOR': '색깔',
    'BLUE': '파랑',
    'ORANGE': '주황',
    'PINK': '핑크',
    'GREEN': '초록',
    'IMAGE_CONFIG': '사진 주소 설정',
    'DEFAULT': '묵인',
    'CHINA_CDN': '국내 가속',
    'CLEAR': '완전히 없애다',
    'EXCEL': 'Excel',
    'CALCULATOR': '계산기',
    'DEBUG': '정보 테스트',
    'UPLOAD': '업로드',
    'IMPORTING': '도입 중',
    'EXPORTING': '도출 중',
    'ADD_TO_TABLE': '양식에 첨가하기',
    'SEPARATE_SCORE': '분단 데이터',
    'ADDUP_SCORE': '누적 데이터',
    'TIP_SEPARATE': '중간에 현시하는거 분단 데이터 입니다',
    'TIP_ADDUP': '오른쪽에 현시하는거 누적 데이터 입니다',
    'TIP_CALCULATOR': '계산기에 진입하고 JSON데이터 도출하기',
    'TIP_EXCEL': '표에서 복제한 데이터를 붙이다. 일렬은 운명이름 입니다, 뒤4열은 운명속성 입니다.',
    'TIP_NEXT_LEVEL': '아직 소모을 기록 하지 않습니다. 다음 관문 진입 하시겠습니까？',
    'TIP_RESET': '리셋 하시겠습니까？',
    'TIP_NO_MATCH_BEFORE': '현재 카팀 통관 요구에 달성 할 수 없기 때문에, 마모 가 더 필요하다.',
    'TIP_NO_MATCH_AFTER': '점',
    'TIP_NO_SETTING': '상대방 진영 설치하다',
    'TIP_REQUEST_FAIL': '요청이 실패했습니다',
    'TIP_FORMAT_ERROR': '데이터 형식 오류 ',
    'TIP_ADD_ALL': '전부 첨가 하시겠습니까？',
    'TIP_CLEAR': '완전히 없애 겠습니까？',
    'TIP_DELETE': '삭제 하시겠습니까？',
    'TIP_REQUIRE_COMPANY_NAME': '회사 이름을 작성해 주세요',
    'TIP_EXISTED_COMPANY_NAME': '회사 이름을 이미 존재합니다',
    'TIP_BAD_PASSWORD': '회사 이름을 존재하지 않는다 혹은 비밀 번호 일치하지 않는다',
    'DAY': '정규',
    'NIGHT': '특집 ',
    'COPY_XUMO': '촬영장 - 허묵',
    'COPY_BAIQI': '촬영장 - 백기',
    'COPY_LIZEYAN': '촬영장 - 이택언',
    'COPY_ZHOUQILUO': '촬영장 - 주기락',
    'COPY': '촬영장',
    'PAY': '충전',
    'CHECKIN': '출석',
    'OBT': '베타서비스',
    'DRAW': '소원',
    'GIFT': '증정',
    'CHALLENGE': '24시간 ',
    'DISASTER': '기타',
    'LIMITED': '한정',
    'TICKET': '시청률',
    'EXCHANGE': 'EVOL샵',
    'UPLOAD_FAIL': '업로드에 실패했습니다',
};